version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ilinskiy
      POSTGRES_PASSWORD: alexander
      POSTGRES_DB: Ilinskiy
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  user_service:
    container_name: game_shop_service
    build: ./game_shop_service/
    ports:
      - "8000:80"
    depends_on:
      - db

  roulette_service:
    restart: on-failure
    container_name: random_game_service
    build: ./random_game_service/
    ports:
      - "8001:80"
    depends_on:
      - db
